services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-test
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - tutorial_network
    deploy:
      resources:
        limits:
          memory: 256M

  kafka:
    image: apache/kafka:latest
    container_name: kafka-test
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=${KAFKA_NODE_ID}
      - KAFKA_PROCESS_ROLES=${KAFKA_PROCESS_ROLES}
      - KAFKA_LISTENERS=${KAFKA_LISTENERS}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_CONTROLLER_LISTENER_NAMES=${KAFKA_CONTROLLER_LISTENER_NAMES}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_CONTROLLER_QUORUM_VOTERS=${KAFKA_CONTROLLER_QUORUM_VOTERS}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
    networks:
      - tutorial_network
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:alpine
    container_name: redis-for-cache
    ports:
      - "6379:6379"
    networks:
      - tutorial_network
    deploy:
      resources:
        limits:
          memory: 128M

  postgres:
    image: postgres:18
    container_name: postgres-tutorial
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Warsaw
    ports:
      - "5432:5432"
    volumes:
      - pg_data_internal:/var/lib/postgresql
      - ./world-1.0.tar.gz:/world-1.0.tar.gz
    networks:
      - tutorial_network
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  pg_data_internal:
    name: tutorial_pg_data

networks:
  tutorial_network:
    name: tutorial_network
